### ISSUE TITLE
zstar() option to suppress plot generation does not suppress plot generation

### ISSUE THREAD

**Issue by jbyoder** [cjcarlson/codependent#5]
I'm trying to set up `zstar()` for non-interactive running on a server, and it looks like even though I've set the `plot` option to FALSE, it's generating the plot. In a quick look through the code I ... don't actually see an `if()` statement that evaluates whether or not to make plots?

**Comment by cjcarlson** [comment]
frowning

**Comment by cjcarlson** [comment]
still frowning

**Comment by cjcarlson** [comment]
I just fixed this. Gotcha
